# Generated by Django 3.1 on 2020-08-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0002_auto_20200810_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktracker',
            name='update_type',
            field=models.CharField(choices=[('da', 'per-day'), ('we', 'Weekly'), ('mo', 'Monthly')], default='da', max_length=10),
        ),
    ]
