# Generated by Django 3.1 on 2020-08-11 10:57

import Scheduler.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0003_auto_20200810_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.IntegerField(unique=True, validators=[Scheduler.models.validateTask]),
        ),
        migrations.AlterField(
            model_name='tasktracker',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scheduler.task', to_field='task_type'),
        ),
    ]
