# Generated by Django 3.1 on 2020-08-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0005_auto_20200811_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_desc',
            field=models.CharField(help_text='Enter Task Description', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.IntegerField(help_text='Enter Task Type'),
        ),
        migrations.AlterField(
            model_name='tasktracker',
            name='email',
            field=models.EmailField(help_text='Enter Email for updates', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='tasktracker',
            name='update_type',
            field=models.CharField(choices=[('daily', 'per-day'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10),
        ),
    ]
