# Generated by Django 3.1 on 2020-08-12 22:51

import Scheduler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0006_auto_20200812_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.IntegerField(help_text='Enter Task Type', validators=[Scheduler.models.validateTask]),
        ),
    ]
